
package no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 10 07:17:43 CEST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
public final class Oppslagstjeneste1405_Oppslagstjeneste_Client {

    private static final QName SERVICE_NAME = new QName("http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-14-05", "oppslagstjeneste-14-05");

    private Oppslagstjeneste1405_Oppslagstjeneste_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception, Exception {
        URL wsdlURL = Oppslagstjeneste1405_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Oppslagstjeneste1405_Service ss = new Oppslagstjeneste1405_Service(wsdlURL, SERVICE_NAME);
        Oppslagstjeneste1405 port = ss.getOppslagstjeneste();  
        
        {
        System.out.println("Invoking hentEndringer...");
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerForespoersel _hentEndringer_hentEndringerForespoersel = new no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerForespoersel();
        java.util.List<no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov> _hentEndringer_hentEndringerForespoerselInformasjonsbehov = new java.util.ArrayList<no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov>();
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov _hentEndringer_hentEndringerForespoerselInformasjonsbehovVal1 = no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov.PERSON;
        _hentEndringer_hentEndringerForespoerselInformasjonsbehov.add(_hentEndringer_hentEndringerForespoerselInformasjonsbehovVal1);
        _hentEndringer_hentEndringerForespoersel.getInformasjonsbehov().addAll(_hentEndringer_hentEndringerForespoerselInformasjonsbehov);
        _hentEndringer_hentEndringerForespoersel.setFraEndringsNummer(-3796092426058438762l);
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons _hentEndringer__return = port.hentEndringer(_hentEndringer_hentEndringerForespoersel);
        System.out.println("hentEndringer.result=" + _hentEndringer__return);


        }
        {
        System.out.println("Invoking hentPersoner...");
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerForespoersel _hentPersoner_hentPersonerForespoersel = new no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerForespoersel();
        java.util.List<no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov> _hentPersoner_hentPersonerForespoerselInformasjonsbehov = new java.util.ArrayList<no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov>();
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov _hentPersoner_hentPersonerForespoerselInformasjonsbehovVal1 = no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.Informasjonsbehov.SIKKER_DIGITAL_POST;
        _hentPersoner_hentPersonerForespoerselInformasjonsbehov.add(_hentPersoner_hentPersonerForespoerselInformasjonsbehovVal1);
        _hentPersoner_hentPersonerForespoersel.getInformasjonsbehov().addAll(_hentPersoner_hentPersonerForespoerselInformasjonsbehov);
        java.util.List<java.lang.String> _hentPersoner_hentPersonerForespoerselPersonidentifikator = new java.util.ArrayList<java.lang.String>();
        java.lang.String _hentPersoner_hentPersonerForespoerselPersonidentifikatorVal1 = "_hentPersoner_hentPersonerForespoerselPersonidentifikatorVal-2066290039";
        _hentPersoner_hentPersonerForespoerselPersonidentifikator.add(_hentPersoner_hentPersonerForespoerselPersonidentifikatorVal1);
        _hentPersoner_hentPersonerForespoersel.getPersonidentifikator().addAll(_hentPersoner_hentPersonerForespoerselPersonidentifikator);
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerRespons _hentPersoner__return = port.hentPersoner(_hentPersoner_hentPersonerForespoersel);
        System.out.println("hentPersoner.result=" + _hentPersoner__return);


        }
        {
        System.out.println("Invoking hentPrintSertifikat...");
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatForespoersel _hentPrintSertifikat_hentPrintSertifikatForespoersel = new no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatForespoersel();
        no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatRespons _hentPrintSertifikat__return = port.hentPrintSertifikat(_hentPrintSertifikat_hentPrintSertifikatForespoersel);
        System.out.println("hentPrintSertifikat.result=" + _hentPrintSertifikat__return);


        }

        System.exit(0);
    }

}
