
/*
 * 
 */

package no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 10 07:17:43 CEST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */
@WebServiceClient(name = "oppslagstjeneste-14-05", 
                  wsdlLocation = "file:/home/janmj/Develop/workspace-4.3.1/SDP/resources/wsdl/oppslagstjeneste-ws-14-05.wsdl",
                  targetNamespace = "http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-14-05") 
public class Oppslagstjeneste1405_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-14-05", "oppslagstjeneste-14-05");
    public final static QName Oppslagstjeneste = new QName("http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-14-05", "oppslagstjeneste");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/janmj/Develop/workspace-4.3.1/SDP/resources/wsdl/oppslagstjeneste-ws-14-05.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Oppslagstjeneste1405_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/janmj/Develop/workspace-4.3.1/SDP/resources/wsdl/oppslagstjeneste-ws-14-05.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Oppslagstjeneste1405_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Oppslagstjeneste1405_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Oppslagstjeneste1405_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    /*
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Oppslagstjeneste1405_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
      
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Oppslagstjeneste1405_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Oppslagstjeneste1405_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
     
    }
	*/
    /**
     * 
     * @return
     *     returns Oppslagstjeneste1405
     */
    @WebEndpoint(name = "oppslagstjeneste")
    public Oppslagstjeneste1405 getOppslagstjeneste() {
        return super.getPort(Oppslagstjeneste, Oppslagstjeneste1405.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Oppslagstjeneste1405
     */
    @WebEndpoint(name = "oppslagstjeneste")
    public Oppslagstjeneste1405 getOppslagstjeneste(WebServiceFeature... features) {
        return super.getPort(Oppslagstjeneste, Oppslagstjeneste1405.class, features);
    }

}
