
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Apr 10 07:17:43 CEST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */

@javax.jws.WebService(
                      serviceName = "oppslagstjeneste-14-05",
                      portName = "oppslagstjeneste",
                      targetNamespace = "http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-14-05",
                      wsdlLocation = "file:/home/janmj/Develop/workspace-4.3.1/SDP/resources/wsdl/oppslagstjeneste-ws-14-05.wsdl",
                      endpointInterface = "no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05.Oppslagstjeneste1405")
                      
public class Oppslagstjeneste1405Impl implements Oppslagstjeneste1405 {

    private static final Logger LOG = Logger.getLogger(Oppslagstjeneste1405Impl.class.getName());

    /* (non-Javadoc)
     * @see no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05.Oppslagstjeneste1405#hentEndringer(no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerForespoersel  hentEndringerForespoersel )*
     */
    public no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons hentEndringer(no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerForespoersel hentEndringerForespoersel) { 
        LOG.info("Executing operation hentEndringer");
        System.out.println(hentEndringerForespoersel);
        try {
            no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons _return = new no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons();
            java.util.List<no.difi.begrep.Person> _returnPerson = new java.util.ArrayList<no.difi.begrep.Person>();
            no.difi.begrep.Person _returnPersonVal1 = new no.difi.begrep.Person();
            _returnPersonVal1.setPersonidentifikator("Personidentifikator553823807");
            no.difi.begrep.Reservasjon _returnPersonVal1Reservasjon = no.difi.begrep.Reservasjon.JA;
            _returnPersonVal1.setReservasjon(_returnPersonVal1Reservasjon);
            no.difi.begrep.Status _returnPersonVal1Status = no.difi.begrep.Status.IKKE_REGISTRERT;
            _returnPersonVal1.setStatus(_returnPersonVal1Status);
            _returnPersonVal1.setBeskrivelse("Beskrivelse-1570895376");
            no.difi.begrep.Kontaktinformasjon _returnPersonVal1Kontaktinformasjon = new no.difi.begrep.Kontaktinformasjon();
            no.difi.begrep.Mobiltelefonnummer _returnPersonVal1KontaktinformasjonMobiltelefonnummer = new no.difi.begrep.Mobiltelefonnummer();
            _returnPersonVal1KontaktinformasjonMobiltelefonnummer.setValue("Value-991197771");
            _returnPersonVal1KontaktinformasjonMobiltelefonnummer.setSistOppdatert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.230+02:00"));
            _returnPersonVal1KontaktinformasjonMobiltelefonnummer.setSistVerifisert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.231+02:00"));
            _returnPersonVal1Kontaktinformasjon.setMobiltelefonnummer(_returnPersonVal1KontaktinformasjonMobiltelefonnummer);
            no.difi.begrep.Epostadresse _returnPersonVal1KontaktinformasjonEpostadresse = new no.difi.begrep.Epostadresse();
            _returnPersonVal1KontaktinformasjonEpostadresse.setValue("Value-1055366723");
            _returnPersonVal1KontaktinformasjonEpostadresse.setSistOppdatert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.232+02:00"));
            _returnPersonVal1KontaktinformasjonEpostadresse.setSistVerifisert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.232+02:00"));
            _returnPersonVal1Kontaktinformasjon.setEpostadresse(_returnPersonVal1KontaktinformasjonEpostadresse);
            _returnPersonVal1.setKontaktinformasjon(_returnPersonVal1Kontaktinformasjon);
            no.difi.begrep.SikkerDigitalPostAdresse _returnPersonVal1SikkerDigitalPostAdresse = new no.difi.begrep.SikkerDigitalPostAdresse();
            _returnPersonVal1SikkerDigitalPostAdresse.setPostkasseadresse("Postkasseadresse957413903");
            _returnPersonVal1SikkerDigitalPostAdresse.setPostkasseleverandoerAdresse("PostkasseleverandoerAdresse-356136928");
            _returnPersonVal1.setSikkerDigitalPostAdresse(_returnPersonVal1SikkerDigitalPostAdresse);
            byte[] _returnPersonVal1X509Sertifikat = new byte[] {};
            _returnPersonVal1.setX509Sertifikat(_returnPersonVal1X509Sertifikat);
            _returnPerson.add(_returnPersonVal1);
            _return.getPerson().addAll(_returnPerson);
            _return.setFraEndringsNummer(659135188003620888l);
            _return.setTilEndringsNummer(3357828707709567208l);
            _return.setSenesteEndringsNummer(1719569533251569476l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05.Oppslagstjeneste1405#hentPersoner(no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerForespoersel  hentPersonerForespoersel )*
     */
    public no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerRespons hentPersoner(no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerForespoersel hentPersonerForespoersel) { 
        LOG.info("Executing operation hentPersoner");
        System.out.println(hentPersonerForespoersel);
        try {
            no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerRespons _return = new no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPersonerRespons();
            java.util.List<no.difi.begrep.Person> _returnPerson = new java.util.ArrayList<no.difi.begrep.Person>();
            no.difi.begrep.Person _returnPersonVal1 = new no.difi.begrep.Person();
            _returnPersonVal1.setPersonidentifikator("Personidentifikator1408443587");
            no.difi.begrep.Reservasjon _returnPersonVal1Reservasjon = no.difi.begrep.Reservasjon.NEI;
            _returnPersonVal1.setReservasjon(_returnPersonVal1Reservasjon);
            no.difi.begrep.Status _returnPersonVal1Status = no.difi.begrep.Status.SLETTET;
            _returnPersonVal1.setStatus(_returnPersonVal1Status);
            _returnPersonVal1.setBeskrivelse("Beskrivelse729372461");
            no.difi.begrep.Kontaktinformasjon _returnPersonVal1Kontaktinformasjon = new no.difi.begrep.Kontaktinformasjon();
            no.difi.begrep.Mobiltelefonnummer _returnPersonVal1KontaktinformasjonMobiltelefonnummer = new no.difi.begrep.Mobiltelefonnummer();
            _returnPersonVal1KontaktinformasjonMobiltelefonnummer.setValue("Value208999318");
            _returnPersonVal1KontaktinformasjonMobiltelefonnummer.setSistOppdatert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.234+02:00"));
            _returnPersonVal1KontaktinformasjonMobiltelefonnummer.setSistVerifisert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.234+02:00"));
            _returnPersonVal1Kontaktinformasjon.setMobiltelefonnummer(_returnPersonVal1KontaktinformasjonMobiltelefonnummer);
            no.difi.begrep.Epostadresse _returnPersonVal1KontaktinformasjonEpostadresse = new no.difi.begrep.Epostadresse();
            _returnPersonVal1KontaktinformasjonEpostadresse.setValue("Value849431455");
            _returnPersonVal1KontaktinformasjonEpostadresse.setSistOppdatert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.234+02:00"));
            _returnPersonVal1KontaktinformasjonEpostadresse.setSistVerifisert(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-07T10:34:37.234+02:00"));
            _returnPersonVal1Kontaktinformasjon.setEpostadresse(_returnPersonVal1KontaktinformasjonEpostadresse);
            _returnPersonVal1.setKontaktinformasjon(_returnPersonVal1Kontaktinformasjon);
            no.difi.begrep.SikkerDigitalPostAdresse _returnPersonVal1SikkerDigitalPostAdresse = new no.difi.begrep.SikkerDigitalPostAdresse();
            _returnPersonVal1SikkerDigitalPostAdresse.setPostkasseadresse("Postkasseadresse187288438");
            _returnPersonVal1SikkerDigitalPostAdresse.setPostkasseleverandoerAdresse("PostkasseleverandoerAdresse-981674080");
            _returnPersonVal1.setSikkerDigitalPostAdresse(_returnPersonVal1SikkerDigitalPostAdresse);
            byte[] _returnPersonVal1X509Sertifikat = new byte[] {};
            _returnPersonVal1.setX509Sertifikat(_returnPersonVal1X509Sertifikat);
            _returnPerson.add(_returnPersonVal1);
            _return.getPerson().addAll(_returnPerson);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see no.difi.kontaktinfo.wsdl.oppslagstjeneste_14_05.Oppslagstjeneste1405#hentPrintSertifikat(no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatForespoersel  hentPrintSertifikatForespoersel )*
     */
    public no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatRespons hentPrintSertifikat(no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatForespoersel hentPrintSertifikatForespoersel) { 
        LOG.info("Executing operation hentPrintSertifikat");
        System.out.println(hentPrintSertifikatForespoersel);
        try {
            no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatRespons _return = new no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentPrintSertifikatRespons();
            _return.setPostkasseleverandoerAdresse("PostkasseleverandoerAdresse-1558211016");
            byte[] _returnX509Sertifikat = new byte[] {};
            _return.setX509Sertifikat(_returnX509Sertifikat);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
