package no.difi.kontaktinfo.wsdl.oppslagstjeneste_16_02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-07-19T09:16:41.764+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-16-02", name = "oppslagstjeneste-16-02")
@XmlSeeAlso({no.difi.begrep.ObjectFactory.class, no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Oppslagstjeneste1602 {

    @WebResult(name = "HentEndringerRespons", targetNamespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02", partName = "HentEndringerRespons")
    @WebMethod(operationName = "HentEndringer")
    public no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentEndringerRespons hentEndringer(
        @WebParam(partName = "HentEndringerForespoersel", name = "HentEndringerForespoersel", targetNamespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentEndringerForespoersel hentEndringerForespoersel
    );

    @WebResult(name = "HentPrintSertifikatRespons", targetNamespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02", partName = "HentPrintSertifikatRespons")
    @WebMethod(operationName = "HentPrintSertifikat")
    public no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPrintSertifikatRespons hentPrintSertifikat(
        @WebParam(partName = "HentPrintSertifikatForespoersel", name = "HentPrintSertifikatForespoersel", targetNamespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPrintSertifikatForespoersel hentPrintSertifikatForespoersel
    );

    @WebResult(name = "HentPersonerRespons", targetNamespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02", partName = "HentPersonerRespons")
    @WebMethod(operationName = "HentPersoner")
    public no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPersonerRespons hentPersoner(
        @WebParam(partName = "HentPersonerForespoersel", name = "HentPersonerForespoersel", targetNamespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPersonerForespoersel hentPersonerForespoersel
    );
}
