package no.difi.kontaktinfo.wsdl.oppslagstjeneste_16_02;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-07-19T09:16:41.771+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "oppslagstjeneste-16-02", 
                  wsdlLocation = "file:///home/janmj/Develop/kontaktregisteret-klient-master/oppslagstjenesten-java-client/src/main/resources/wsdl/oppslagstjeneste-ws-16-02.wsdl",
                  targetNamespace = "http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-16-02") 
public class Oppslagstjeneste1602_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-16-02", "oppslagstjeneste-16-02");
    public final static QName OppslagstjenesteSOAP12 = new QName("http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-16-02", "oppslagstjeneste_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL("file:///home/janmj/Develop/kontaktregisteret-klient-master/oppslagstjenesten-java-client/src/main/resources/wsdl/oppslagstjeneste-ws-16-02.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Oppslagstjeneste1602_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:///home/janmj/Develop/kontaktregisteret-klient-master/oppslagstjenesten-java-client/src/main/resources/wsdl/oppslagstjeneste-ws-16-02.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Oppslagstjeneste1602_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Oppslagstjeneste1602_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Oppslagstjeneste1602_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /*
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Oppslagstjeneste1602_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Oppslagstjeneste1602_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Oppslagstjeneste1602_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }
	*/
    
    /**
     *
     * @return
     *     returns Oppslagstjeneste1602
     */
    @WebEndpoint(name = "oppslagstjeneste_SOAP12")
    public Oppslagstjeneste1602 getOppslagstjenesteSOAP12() {
        return super.getPort(OppslagstjenesteSOAP12, Oppslagstjeneste1602.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Oppslagstjeneste1602
     */
    @WebEndpoint(name = "oppslagstjeneste_SOAP12")
    public Oppslagstjeneste1602 getOppslagstjenesteSOAP12(WebServiceFeature... features) {
        return super.getPort(OppslagstjenesteSOAP12, Oppslagstjeneste1602.class, features);
    }

}
