
package no.difi.kontaktinfo.wsdl.oppslagstjeneste_16_02;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-07-19T09:16:41.711+02:00
 * Generated source version: 2.7.0
 * 
 */
public final class Oppslagstjeneste1602_OppslagstjenesteSOAP12_Client {

    private static final QName SERVICE_NAME = new QName("http://kontaktinfo.difi.no/wsdl/oppslagstjeneste-16-02", "oppslagstjeneste-16-02");

    private Oppslagstjeneste1602_OppslagstjenesteSOAP12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Oppslagstjeneste1602_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Oppslagstjeneste1602_Service ss = new Oppslagstjeneste1602_Service(wsdlURL, SERVICE_NAME);
        Oppslagstjeneste1602 port = ss.getOppslagstjenesteSOAP12();  
        
        {
        System.out.println("Invoking hentEndringer...");
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentEndringerForespoersel _hentEndringer_hentEndringerForespoersel = null;
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentEndringerRespons _hentEndringer__return = port.hentEndringer(_hentEndringer_hentEndringerForespoersel);
        System.out.println("hentEndringer.result=" + _hentEndringer__return);


        }
        {
        System.out.println("Invoking hentPrintSertifikat...");
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPrintSertifikatForespoersel _hentPrintSertifikat_hentPrintSertifikatForespoersel = null;
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPrintSertifikatRespons _hentPrintSertifikat__return = port.hentPrintSertifikat(_hentPrintSertifikat_hentPrintSertifikatForespoersel);
        System.out.println("hentPrintSertifikat.result=" + _hentPrintSertifikat__return);


        }
        {
        System.out.println("Invoking hentPersoner...");
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPersonerForespoersel _hentPersoner_hentPersonerForespoersel = null;
        no.difi.kontaktinfo.xsd.oppslagstjeneste._16_02.HentPersonerRespons _hentPersoner__return = port.hentPersoner(_hentPersoner_hentPersonerForespoersel);
        System.out.println("hentPersoner.result=" + _hentPersoner__return);


        }

        System.exit(0);
    }

}
